wrapperVersion=3.3.2
distributionUrl=https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip
distributionSha256Sum=404b6e15e32ea6a2a63e25315ad6131cf99b0cc4ee2c08458c4e40bf24bceaac
